import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicFooter, PublicHeader } from "@/app/components/public-chrome";
import { publicPageMetadata } from "@/lib/seo/metadata";

const content = {
  about: { title: "About SteadFast", intro: "A clearer, more connected way to search, present, and manage Jamaican property.", sections: [["Built for property professionals", "SteadFast gives brokerages and agents a shared approval-led platform for publishing reliable listings and serving clients with confidence."], ["Built for buyers and renters", "Visitors can search active properties, explore the professionals behind them, and choose the agent they want to contact."]] },
  careers: { title: "Careers", intro: "Help build the modern property platform for Jamaica and the Caribbean.", sections: [["Work with purpose", "We are building a practical service for real estate professionals and the people they serve."], ["Future opportunities", "We expect roles across customer operations, partner success, real estate data, design, and engineering as SteadFast grows."]] },
  feedback: { title: "Feedback", intro: "Tell us what would make SteadFast easier, clearer, or more useful.", sections: [["Your perspective matters", "We review feedback from property seekers, agents, brokerages, and partners as we improve the platform."], ["Share feedback", "For the current prototype, send your feedback to support@canadasap.com with the page name and a short description."]] },
  advertise: { title: "Advertise with SteadFast", intro: "Put your brokerage or professional profile in front of serious Jamaican property searchers.", sections: [["Recommended placements", "Featured brokerage and agent placements are managed by SteadFast to keep the marketplace useful and professional."], ["Coming soon", "Advertising packages will be introduced after the pilot, with transparent placement rules and clear labelling."]] },
  support: { title: "Support", intro: "Practical help for visitors, agents, brokerages, and SteadFast customers.", sections: [["For property seekers", "Use Search to filter active listings and choose the professional you wish to contact."], ["For professionals", "Sign in to manage listings, review approvals, and update your public professional website."], ["Need help?", "Email support@canadasap.com and include the page you were using plus a screenshot if possible."]] },
  privacy: { title: "Privacy", intro: "We handle personal information carefully and only for providing and improving SteadFast services.", sections: [["Information we use", "Account, inquiry, listing, and support details are used to operate the platform, deliver requested services, and protect the marketplace."], ["Your choices", "You may request access to or correction of your account information through SteadFast Support. This draft policy will be replaced with the formal launch policy before public release."]] },
  terms: { title: "Terms", intro: "Clear responsibilities for everyone using the SteadFast platform.", sections: [["Marketplace role", "SteadFast provides technology for publishing and discovering property. Brokerages remain responsible for approvals, listing accuracy, and professional conduct."], ["Pilot terms", "This prototype is for testing. Formal subscription and platform terms will be issued before commercial launch."]] },
} as const;
export type InformationSlug = keyof typeof content;
export function informationMetadata(slug: InformationSlug): Metadata { const page = content[slug]; return publicPageMetadata({ title: page.title, description: page.intro, path: `/${slug}` }); }
export function PublicInformationPage({ slug }: { slug: InformationSlug }) { const page = content[slug]; if (!page) notFound(); return <main className="public-information-page"><PublicHeader /><section className="public-information-hero"><span>SteadFast</span><h1>{page.title}</h1><p>{page.intro}</p></section><section className="public-information-content">{page.sections.map(([heading, body]) => <article key={heading}><h2>{heading}</h2><p>{body}</p></article>)}</section><PublicFooter /></main>; }
