import Link from "next/link";
import { AccountHeader } from "@/app/components/account-header";
import { StatusMessage } from "@/app/components/status-message";
import { saveFeaturedBrokerageAction } from "@/app/actions/platform-recommendations";
import { getActiveMembershipContext, requireInternalMfa } from "@/lib/auth/session";
import { deriveWorkspaceAccess } from "@/lib/auth/workspace-access";
import { createAdminClient } from "@/lib/supabase/admin";
import { redirect } from "next/navigation";
export const dynamic = "force-dynamic";
export default async function RecommendationsPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) { const query = await searchParams; const context = await getActiveMembershipContext("/workspace/recommendations"); const access = deriveWorkspaceAccess({ hasMembership: Boolean(context.membership), roles: context.roles, permissions: context.permissions, platformRoles: context.platformRoles }); if (!access.isOperations && !access.isAdmin) redirect("/access-denied?reason=platform-recommendations"); await requireInternalMfa(context, "/workspace/recommendations"); const admin = createAdminClient(); const [{ data: sites }, { data: featured }] = await Promise.all([admin.from("professional_sites").select("owner_brokerage_id,display_name,slug").eq("site_type", "brokerage").eq("status", "active").order("display_name"), admin.from("platform_featured_brokerages").select("brokerage_id,display_rank").eq("is_active", true)]); const ranks = new Map((featured ?? []).map((item) => [item.brokerage_id, item.display_rank])); return <main className="account-page"><AccountHeader displayName={context.person.display_name} hasWorkspace canManageAgents={false} canManageListings={false} canReviewListings={false} canManageInquiries={false} canShareListings={false}/><section className="account-hero compact"><span className="eyebrow"><i/>SteadFast management</span><h1>Recommended brokerages.</h1><p>Set the four brokerage placements shown on the public home page. Leave a rank empty to remove it.</p></section><section className="account-main settings-main"><StatusMessage notice={query.notice} error={query.error}/><div className="account-card"><div className="card-heading"><span>Homepage placement</span><h2>Brokerage ranking</h2></div><div className="recommendation-admin-list">{sites?.map((site) => <form action={saveFeaturedBrokerageAction} key={site.owner_brokerage_id} className="recommendation-admin-row"><input type="hidden" name="brokerageId" value={site.owner_brokerage_id!}/><div><strong>{site.display_name}</strong><small>/{site.slug}</small></div><label><span>Rank</span><select name="rank" defaultValue={ranks.get(site.owner_brokerage_id!)?.toString() ?? ""}><option value="">Not featured</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label><button className="solid-button" type="submit">Save</button></form>)}</div><Link className="outline-dark-button" href="/workspace">Back to workspace</Link></div></section></main>; }
